"""
Bhasha Setu — Video URL Downloader
Downloads videos from YouTube and 1000+ other sites using yt-dlp.

Supports: YouTube, Vimeo, Instagram, Twitter/X, Facebook, Dailymotion,
          TED, Bilibili, Reddit, and most public video platforms.

Quality cap: 720p MP4 — keeps file sizes manageable for the dubbing pipeline.

Public API:
    get_video_info(url)        → metadata dict (no download, instant)
    download_to_temp(url, ...) → local temp path (pipeline handles S3 upload)
"""

import os
import tempfile
import logging
from typing import Callable, Optional

log = logging.getLogger(__name__)

MAX_HEIGHT = 720

_PLATFORM_MAP = {
    "youtube":     "YouTube",
    "vimeo":       "Vimeo",
    "instagram":   "Instagram",
    "twitter":     "Twitter / X",
    "facebook":    "Facebook",
    "dailymotion": "Dailymotion",
    "ted":         "TED",
    "bilibili":    "Bilibili",
    "reddit":      "Reddit",
}

_FORMAT = (
    f"bestvideo[height<={MAX_HEIGHT}][ext=mp4]+bestaudio[ext=m4a]"
    f"/bestvideo[height<={MAX_HEIGHT}]+bestaudio"
    f"/best[height<={MAX_HEIGHT}][ext=mp4]"
    f"/best[height<={MAX_HEIGHT}]"
    f"/best"
)

# Realistic Chrome user-agent — avoids most platform bot-detection
_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/125.0.0.0 Safari/537.36"
)


def _platform(info: dict) -> str:
    extractor = info.get("extractor_key", "").lower()
    return next(
        (v for k, v in _PLATFORM_MAP.items() if k in extractor),
        extractor.capitalize() or "Unknown"
    )


def _friendly_error(e) -> str:
    msg = str(e)
    if "Private video"    in msg: return "This video is private and cannot be accessed."
    if "age"              in msg.lower(): return "This video is age-restricted."
    if "unavailable"      in msg.lower(): return "This video is unavailable or has been removed."
    if "removed"          in msg.lower(): return "This video has been removed."
    if "copyright"        in msg.lower(): return "Video unavailable due to copyright restrictions."
    if "confirm your age" in msg.lower(): return "This video requires sign-in to watch."
    if "403"              in msg: return "YouTube blocked the request (403). Try updating yt-dlp: pip install --upgrade yt-dlp"
    return f"Could not access video: {msg[:200]}"


def _convert_json_cookies_to_netscape(file_path: str):
    """If file is JSON cookies, convert it to Netscape format in-place."""
    import json
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read().strip()
        if not (content.startswith("[") and content.endswith("]")):
            return # Not JSON
            
        cookies = json.loads(content)
        lines = ["# Netscape HTTP Cookie File\n# This file was generated by Bhasha Setu from JSON cookies\n"]
        for c in cookies:
            domain = c.get("domain", "")
            if not domain: continue
            
            # Subdomains flag: TRUE if domain starts with '.'
            subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            exp = c.get("expirationDate")
            exp_str = str(int(exp)) if exp is not None else "0"
            name = c.get("name", "")
            value = c.get("value", "")
            
            lines.append(f"{domain}\t{subdomains}\t{path}\t{secure}\t{exp_str}\t{name}\t{value}\n")
            
        with open(file_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
        log.info(f"Converted JSON cookies file to Netscape format: {file_path}")
    except Exception as e:
        log.warning(f"Failed to check/convert JSON cookies: {e}")


def _make_opts(extra: dict = {}) -> dict:
    """Base yt-dlp options shared by all calls."""
    opts = {
        "quiet":       True,
        "no_warnings": True,
        "noplaylist":  True,
        "http_headers": {"User-Agent": _UA},
        "extractor_args": {"youtube": {"player_client": ["android", "ios"]}},
        **extra,
    }
    
    # Auto-detect cookies.txt uploaded by the user to bypass YouTube datacenter blocks
    for path in ["cookies.txt", "/content/cookies.txt"]:
        if os.path.exists(path):
            _convert_json_cookies_to_netscape(path)
            log.info(f"Using cookies file: {path}")
            opts["cookiefile"] = path
            break
            
    return opts


def _with_cookie_fallback(build_opts_fn, run_fn):
    """
    Try run_fn(opts_with_chrome_cookies), fall back to run_fn(opts_without_cookies)
    if Chrome is not installed or cookies can't be read.
    """
    try:
        opts = build_opts_fn(cookies=True)
        return run_fn(opts)
    except Exception as e:
        err = str(e).lower()
        # If the error is about cookies/browser, retry without them
        if any(w in err for w in ("chrome", "cookie", "browser", "keyring")):
            log.warning(f"Cookie read failed ({e}), retrying without cookies…")
            opts = build_opts_fn(cookies=False)
            return run_fn(opts)
        raise


# ── Public: metadata fetch ────────────────────────────────────────────────────

def get_video_info(url: str) -> dict:
    """
    Fetch video metadata WITHOUT downloading. Fast (~1-2 seconds).

    Returns dict: title, duration (seconds|None), thumbnail (url|None),
                  uploader (str|None), platform (str), url (str)

    Raises ValueError for private/unavailable/bad URLs.
    Raises RuntimeError if yt-dlp is not installed.
    """
    try:
        import yt_dlp
    except ImportError:
        raise RuntimeError("yt-dlp not installed. Run: pip install yt-dlp")

    def _build(cookies: bool):
        o = _make_opts({"skip_download": True})
        if cookies:
            o["cookiesfrombrowser"] = ("chrome",)
        return o

    def _run(opts):
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
            if not info:
                raise ValueError("Could not fetch video information.")
            return info

    try:
        info = _with_cookie_fallback(_build, _run)
        return {
            "title":     info.get("title", "Untitled Video"),
            "duration":  info.get("duration"),
            "thumbnail": info.get("thumbnail"),
            "uploader":  info.get("uploader") or info.get("channel"),
            "platform":  _platform(info),
            "url":       url,
        }
    except yt_dlp.utils.DownloadError as e:
        raise ValueError(_friendly_error(e))


# ── Public: download to temp ──────────────────────────────────────────────────

def _extract_youtube_id(url: str) -> Optional[str]:
    import re
    patterns = [
        r"(?:v=|\/v\/|embed\/|shorts\/|\/youtu\.be\/)([a-zA-Z0-9_-]{11})",
        r"(?:watch\?v=)([a-zA-Z0-9_-]{11})"
    ]
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1)
    return None


def _download_via_piped(url: str, output_path: str) -> bool:
    import json
    import urllib.request
    import shutil
    
    video_id = _extract_youtube_id(url)
    if not video_id:
        return False
        
    log.info(f"Attempting to download YouTube video {video_id} via Piped API fallback...")
    
    instances = [
        "https://pipedapi.kavin.rocks",
        "https://api.piped.yt",
        "https://pipedapi.col1a.dedyn.io",
        "https://piped-api.lunar.icu"
    ]
    
    for base_url in instances:
        try:
            api_url = f"{base_url}/streams/{video_id}"
            req = urllib.request.Request(
                api_url, 
                headers={"User-Agent": "Mozilla/5.0"}
            )
            with urllib.request.urlopen(req, timeout=10) as response:
                data = json.loads(response.read().decode('utf-8'))
                
            video_streams = data.get("videoStreams", [])
            if not video_streams:
                continue
                
            # Filter for mp4
            mp4_streams = [s for s in video_streams if "mp4" in s.get("mimeType", "").lower() or s.get("format", "").lower() == "mpeg-4"]
            if not mp4_streams:
                mp4_streams = video_streams
                
            selected_stream = None
            for q in ["720p", "480p", "360p"]:
                for s in mp4_streams:
                    if s.get("quality") == q:
                        selected_stream = s
                        break
                if selected_stream:
                    break
                    
            if not selected_stream:
                selected_stream = mp4_streams[0]
                
            stream_url = selected_stream.get("url")
            if not stream_url:
                continue
                
            log.info(f"Piped stream URL found! Downloading stream from: {base_url}")
            
            stream_req = urllib.request.Request(
                stream_url, 
                headers={"User-Agent": "Mozilla/5.0"}
            )
            with urllib.request.urlopen(stream_req, timeout=30) as src, open(output_path, "wb") as dst:
                shutil.copyfileobj(src, dst)
                
            log.info(f"Successfully downloaded YouTube video via Piped stream: {output_path}")
            return True
            
        except Exception as e:
            log.warning(f"Piped instance {base_url} failed: {e}")
            continue
            
    return False


def download_to_temp(
    url:         str,
    progress_cb: Optional[Callable[[float, str], None]] = None,
) -> str:
    """
    Download a video from URL to a system temp file. Returns the local path.
    """
    try:
        import yt_dlp
    except ImportError:
        raise RuntimeError("yt-dlp not installed. Run: pip install yt-dlp")

    tmp_dir  = tempfile.mkdtemp(prefix="bhasha_setu_")
    out_tmpl = os.path.join(tmp_dir, "%(id)s.%(ext)s")
    _last    = [-1.0]

    def _hook(d: dict):
        if not progress_cb:
            return
        status = d.get("status", "")
        if status == "downloading":
            total = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
            done  = d.get("downloaded_bytes", 0)
            pct   = min(95.0, (done / total * 100) if total else _last[0] + 0.5)
            if pct - _last[0] >= 1.0:
                _last[0] = pct
                speed = (d.get("speed") or 0) / (1024 * 1024)
                eta   = d.get("eta") or 0
                msg   = f"Fetching video… {pct:.0f}%"
                if speed > 0.01: msg += f" · {speed:.1f} MB/s"
                if eta   > 0:    msg += f" · ~{eta}s left"
                progress_cb(pct, msg)
        elif status == "finished":
            progress_cb(97.0, "Merging audio & video streams…")

    def _build(cookies: bool):
        o = _make_opts({
            "format":              _FORMAT,
            "outtmpl":             out_tmpl,
            "progress_hooks":      [_hook],
            "merge_output_format": "mp4",
            "retries":             5,
            "fragment_retries":    5,
        })
        if cookies:
            o["cookiesfrombrowser"] = ("chrome",)
        return o

    def _run(opts):
        with yt_dlp.YoutubeDL(opts) as ydl:
            return ydl.extract_info(url, download=True)

    try:
        if progress_cb:
            progress_cb(0.0, "Connecting to video source…")

        fallback_triggered = False
        actual = ""

        try:
            info = _with_cookie_fallback(_build, _run)
        except Exception as yt_err:
            if "youtube" in url.lower() or "youtu.be" in url.lower():
                log.warning(f"yt-dlp download failed: {yt_err}. Trying Piped API fallback...")
                if progress_cb:
                    progress_cb(10.0, "YouTube blocked checking. Using mirror download...")
                actual = os.path.join(tmp_dir, "downloaded.mp4")
                if _download_via_piped(url, actual):
                    fallback_triggered = True
                    info = {"dummy": True}
                else:
                    raise yt_err
            else:
                raise yt_err

        if not info:
            raise ValueError("Download returned no information.")

        # Find the output file if fallback was not triggered
        if not fallback_triggered:
            mp4s = sorted(
                [os.path.join(tmp_dir, f) for f in os.listdir(tmp_dir)
                 if f.endswith(".mp4")],
                key=os.path.getmtime,
            )
            if not mp4s:
                all_vids = sorted(
                    [os.path.join(tmp_dir, f) for f in os.listdir(tmp_dir)
                     if os.path.splitext(f)[1] in (".mp4", ".mkv", ".webm")],
                    key=os.path.getmtime,
                )
                if not all_vids:
                    raise RuntimeError("Download finished but no output file found.")
                actual = all_vids[-1]
            else:
                actual = mp4s[-1]

        size_mb = os.path.getsize(actual) / (1024 * 1024)
        if progress_cb:
            progress_cb(100.0, f"Video ready — {size_mb:.1f} MB")
        log.info(f"Temp download: {actual} ({size_mb:.1f} MB)")
        return actual

    except yt_dlp.utils.DownloadError as e:
        raise ValueError(_friendly_error(e))
    except Exception as e:
        raise RuntimeError(f"Unexpected download error: {e}") from e
